/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIdRouteImport } from './routes/decks.$id'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdRoute = DecksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/decks/$id': typeof DecksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/decks/$id': typeof DecksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/decks': typeof DecksRouteWithChildren
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/decks/$id': typeof DecksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/decks'
    | '/finance'
    | '/inventory'
    | '/decks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards' | '/decks' | '/finance' | '/inventory' | '/decks/$id'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/decks'
    | '/finance'
    | '/inventory'
    | '/decks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DecksRoute: typeof DecksRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$id': {
      id: '/decks/$id'
      path: '/$id'
      fullPath: '/decks/$id'
      preLoaderRoute: typeof DecksIdRouteImport
      parentRoute: typeof DecksRoute
    }
  }
}

interface DecksRouteChildren {
  DecksIdRoute: typeof DecksIdRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksIdRoute: DecksIdRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DecksRoute: DecksRouteWithChildren,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
